using FastEndpoints;
using Microsoft.EntityFrameworkCore;

namespace ManualAutoGeneratedIds.Endpoints;

public class GetCreditCardEndpoint : Endpoint<GetCreditCardRequest, GetCreditCardResponse>
{
    private readonly Context context;

    public GetCreditCardEndpoint(Context context)
    {
        this.context = context;
    }

    public override void Configure()
    {
        AllowAnonymous();
        Get("cc/{id}");
    }

    public override async Task<GetCreditCardResponse> ExecuteAsync(GetCreditCardRequest req, CancellationToken ct)
    {
        var cc = await context.CreditCards.FirstAsync(x => x.Id == req.Id);
        return new GetCreditCardResponse(cc);
    }
}

public record GetCreditCardRequest(CreditCardId Id);

public record GetCreditCardResponse(CreditCard CreditCard);