using FastEndpoints;
using Microsoft.EntityFrameworkCore;

namespace ManualAutoGeneratedIds.Endpoints;

public class PostProductEndpoint : Endpoint<PostProductRequest, PostProductResponse>
{
    private readonly Context context;

    public PostProductEndpoint(Context context)
    {
        this.context = context;
    }

    public override void Configure()
    {
        AllowAnonymous();
        Post("product");
    }

    public override async Task<PostProductResponse> ExecuteAsync(PostProductRequest req, CancellationToken ct)
    {
        var product = await context.Products.FirstAsync(x => x.Id == req.Id);
        return new PostProductResponse(product);
    }
}

public record PostProductRequest(ProductId Id);

public record PostProductResponse(Product Product);