using Microsoft.EntityFrameworkCore;

namespace ManualAutoGeneratedIds;

public class Context : DbContext
{
    public DbSet<Product> Products { get; set; }
    public DbSet<CreditCard> CreditCards { get; set; }
    public DbSet<Person> Persons { get; set; }
    public DbSet<Normal> Normals { get; set; }

    public Context(DbContextOptions<Context> options) : base(options)
    {
    }

    protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)
    {
        configurationBuilder.ApplyTypedIdConversions();

        // Without Generic Magic
        // configurationBuilder
        //     .Properties<CompanyId>()
        //     .HaveConversion<TypedIdConverter<CompanyId>>();
        //     
        // configurationBuilder
        //     .Properties<InstructionId>()
        //     .HaveConversion(typeof(TypedIdConverter<InstructionId>));
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.RegisterTypedIdValueGenerators();

        // Without Generic Magic
        // modelBuilder.Entity<Person>()
        //     .Property(x => x.Id)
        //     .ValueGeneratedOnAdd()
        //     .HasValueGenerator<TypedIdValueGenerator<PersonId>>();
        //
        // modelBuilder.Entity<CreditCard>()
        //     .Property(x => x.Id)
        //     .ValueGeneratedOnAdd()
        //     .HasValueGenerator<TypedIdValueGenerator<CreditCardId>>();

        modelBuilder.Entity<Person>()
            .OwnsOne(x => x.LocalizedStr, x => x.ToJson());

        base.OnModelCreating(modelBuilder);
    }
}

public record CreditCardId : TypedId
{
    protected override string prefix => "cc";
}

public class CreditCard
{
    public CreditCardId Id { get; set; }
    public string CVC { get; set; } = "";

    public PersonId PersonId { get; set; }
    public Person Person { get; set; }
}

public record ProductId : TypedId
{
    protected override string prefix => "prd";
}

public class Product
{
    public ProductId Id { get; set; }
    public string Description { get; set; } = "";
}

public class Normal
{
    public Guid Id { get; set; }
    public string SomeString { get; set; } = "";
}

public record PersonId : TypedId
{
    protected override string prefix => "guy";
}

public class Person
{
    public PersonId Id { get; set; }
    public int Age { get; set; }
    public LocalizedString LocalizedStr { get; set; } = new();

    public List<CreditCard> CreditCards { get; set; } = new();
}

public record LocalizedString
{
    public string De { get; set; } = "";
    public string En { get; set; } = "";
    public string Uk { get; set; } = "";
}